### ISSUE TITLE
Prescription refill (POST) endpoint into gem

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/va_rx#7]

**Comment by saneshark** [comment]
@ayaleloehr I've stubbed this method and added a failing spec (for the error that prescription cannot be refilled) - it should be in master. I had to do this to get simplecov over 90% for client.rb but I think it will help prove useful for writing additional specs to test with successful refill as well.

**Comment by ayaleloehr** [comment]
The post is now working on the VA API, so there should be no more blocker on this issue.

**Comment by ayaleloehr** [comment]
@cfeeney-va added this in https://github.com/department-of-veterans-affairs/va_rx/pull/16

**Comment by ayaleloehr** [comment]
@cfeeney-va added this in https://github.com/department-of-veterans-affairs/va_rx/pull/16
